### PR TITLE
Cache length.

### PR DESCRIPTION
**Pull request by hemanth**
^

### CODE REVIEW

**Comment by ryanseys** [comment]
I like using [`Array#forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) for this kinda thing. Makes for some seriously clean code.

``` js
x.forEach(function(i) {
  sum += i;
});
```

Or get rid of sum all together by reducing the array:

``` js
return x.reduce(function(prev, curr) { 
  return prev + curr;
}, 0);
```

**Comment by hemanth** [comment]
@ryanseys I would have voted for `reduce` but it's slower, could have linked to a jspref but it's down.

**Comment by sindresorhus** [comment]
V8 caches the length for you, so this is moot. While I usually use `forEach`, it's intentionally using a for-loop to be as fast as possible. `forEach` and similar methods aren't very optimized in V8 yet and comes with the overhead of calling a function for each iteration.

**Comment by hemanth** [comment]
:+1: 

But if one browserify it and use it elsewhere other than `v8` ?

**Pull request closed without merging**
